name: Build Pixel Kernel with KernelSU

permissions:
  contents: read  # 不需要写入 release 或打 tag
  actions: read

on:
  workflow_dispatch:
    inputs:
      build_redbull:
        description: 'Build redbull 4.19 kernel?'
        required: true
        type: boolean
        default: true

jobs:
  build-kernel-redbull:
    uses: ./.github/workflows/build-kernel-redbull.yml
    secrets: inherit
    if: ${{ inputs.build_redbull }}
