name: Build Pixel5 Kernel


permissions:
  contents: read  
  actions: read

on:
  workflow_dispatch:
    inputs:
      build_redbull:
        description: 'Build Pixel5 Android14 Kernel'
        required: true
        type: boolean
        default: true



jobs:
  build-kernel-4-19-kernelsu-susfs:
    runs-on: ubuntu-22.04

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 8192    # 8GB for root memory reservation
          temp-reserve-mb: 2048     # 2GB for temporary memory reservation
          swap-size-mb: 8192       # 8GB for swap size
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Get build space
        run: |
          free -h
          df -h

      - name: Set CONFIG Environment Variable
        run: |
          # Set CONFIG dynamically based on matrix values
          CONFIG="redbull"
          
          # Set CONFIG as an environment variable for future steps
          echo "CONFIG=$CONFIG" >> $GITHUB_ENV
          
          echo "CONFIG set to: $CONFIG"

      - name: Install Repo
        run: |
          # Install dependencies
          mkdir -p ./git-repo
          curl https://storage.googleapis.com/git-repo-downloads/repo > ./git-repo/repo
          chmod a+rx ./git-repo/repo
          echo "REPO=$GITHUB_WORKSPACE/./git-repo/repo" >> $GITHUB_ENV

      - name: Install Others
        run: |
          # Install dependencies
          sudo apt update
          sudo apt install build-essential flex bison libssl-dev libelf-dev libncurses5-dev gcc-aarch64-linux-gnu make

      - run: ls -l


      - name: Initialize and Sync Kernel Source
        run: |

          mkdir -p "$CONFIG"
          
          cd "$CONFIG"
          
          # Initialize and sync kernel source
          echo "Initializing and syncing kernel source..."
          $REPO init -u https://android.googlesource.com/kernel/manifest -b android-msm-redbull-4.19-android14-qpr3 --repo-rev=v2.54 --depth=1

          # Sync repo and apply patches
          $REPO --version
          $REPO --trace sync -c -j$(nproc --all) --no-tags --fail-fast
          

      - name: Run sed and perl Commands
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG/private/msm-google/"

          export LOCALVERSION="-g7b0944645172-ab10812814-NekomiyaMidori-SSR"
          export LOCALVERSION_AUTO=n


      - name: Build the Kernel
        run: |
          echo "Changing to configuration directory: $CONFIG..."
          cd "$CONFIG"
          
          export LOCALVERSION="-g7b0944645172-ab10812814-NekomiyaMidori-SSR"
          export LOCALVERSION_AUTO=n
          
          echo "Building the kernel..."
          BUILD_AOSP_KERNEL=1 ./build_redbull.sh

      - name: boot.img
        uses: actions/upload-artifact@v4
        with:
          name: boot.img
          path: "redbull/out/android-msm-pixel-4.19/dist/boot.img"
          
      - name: vendor_boot.img
        uses: actions/upload-artifact@v4
        with:
          name: vendor_boot.img
          path: "redbull/out/android-msm-pixel-4.19/dist/vendor_boot.img"

      - name: dtbo.img
        uses: actions/upload-artifact@v4
        with:
          name: dtbo.img
          path: "redbull/out/android-msm-pixel-4.19/dist/dtbo.img"















            
